### ISSUE TITLE
Use standard Rancher/Cattle environment variables

### ISSUE THREAD

**Issue by etlweather** [Gmentsik/ranch2git#1]
Hi, this looks like a good tool. Can you make it use the standard environment variables for Rancher URL, User and Password - covered in [Service Accounts in Rancher](http://docs.rancher.com/rancher/latest/en/rancher-services/service-accounts/)?

- `CATTLE_ACCESS_KEY`
- `CATTLE_SECRET_KEY`
- `CATTLE_URL`

**Comment by N1v0k** [comment]
Hi,

thanks for the feedback.

Do you mean to replace the variables:

`RANCHER_APIV2_URL	`-> `CATTLE_URL`
`RANCHER_API_USER	`-> `CATTLE_ACCESS_KEY`
`RANCHER_API_PASS       `-> `CATTLE_SECRET_KEY`?

**Comment by etlweather** [comment]
Well, I think you may want to support both so you're backward compatible.

**Comment by N1v0k** [comment]
Okay I see, so we are talking about V1 and the service accounts here, since the above link isn't working for me, this is the correct one:

http://docs.rancher.com/rancher/v1.2/en/rancher-services/service-accounts/

I will check this out.

**Comment by etlweather** [comment]
Oh. I didn't realize. I haven't moved to >= 1.2 yet.

**Comment by N1v0k** [comment]
Should work now, could you please take a look at the newest image and report back if this issue can be closed?

**Comment by etlweather** [comment]
Thanks. Unfortunately, I think there is more needed to make it work with v1 api. I made a fork, will check this out and will send a pull request once I have it working with v1.

**Comment by N1v0k** [comment]
Strange, I have tested it just with providing the labels and it worked but only with the newest version.

Can you show me the logs?

**Comment by etlweather** [comment]
Sure, here are the logs. What I found is that it is going to
`/v1/stacks` which returns 404. In v1, it's `/v1/environments`.


2/23/2017 9:47:17 AM[v0.4] [23.02.2017]
2/23/2017 9:47:17 AMStarting up ... cleaning.
2/23/2017 9:47:19 AMFetching rancher stacks ... Exception in thread
"main" org.json.JSONException: JSONObject["data"] not found.
2/23/2017 9:47:19 AM	at org.json.JSONObject.get(JSONObject.java:473)
2/23/2017 9:47:19 AM	at
org.json.JSONObject.getJSONArray(JSONObject.java:555)
2/23/2017 9:47:19 AM	at
ly.gerge.rancher2git.rancher.RancherInstance.fetchRancherStacks(RancherInstance.java:68)
2/23/2017 9:47:19 AM	at
ly.gerge.rancher2git.Rancher2git.main(Rancher2git.java:43)
2/23/2017 10:47:20 AMStarting up ... cleaning.
2/23/2017 10:47:21 AMFetching rancher stacks ... Exception in thread
"main" org.json.JSONException: JSONObject["data"] not found.
2/23/2017 10:47:21 AM	at org.json.JSONObject.get(JSONObject.java:473)
2/23/2017 10:47:21 AM	at
org.json.JSONObject.getJSONArray(JSONObject.java:555)
2/23/2017 10:47:21 AM	at
ly.gerge.rancher2git.rancher.RancherInstance.fetchRancherStacks(RancherInstance.java:68)

2/23/2017 10:47:21 AM	at
ly.gerge.rancher2git.Rancher2git.main(Rancher2git.java:43)
2/23/2017 11:47:21 AMStarting up ... cleaning.
2/23/2017 11:47:22 AMFetching rancher stacks ... Exception in thread
"main" org.json.JSONException: JSONObject["data"] not found.
2/23/2017 11:47:22 AM	at org.json.JSONObject.get(JSONObject.java:473)
2/23/2017 11:47:22 AM	at
org.json.JSONObject.getJSONArray(JSONObject.java:555)
2/23/2017 11:47:22 AM	at
ly.gerge.rancher2git.rancher.RancherInstance.fetchRancherStacks(RancherInstance.java:68)

2/23/2017 11:47:22 AM	at
ly.gerge.rancher2git.Rancher2git.main(Rancher2git.java:43)

**Comment by N1v0k** [comment]
OK I see the problem here. It appears that API v2 calls are redirected to v2 if try to call them on V1 this is why it worked on my setup.

Can you provide me with the API Url that starts the download of Config Zip file?
I can't seem to find one. If this is not possible with v1 I will have to fetch the configs from the JSON and write it on disk.
